services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./laravel:/var/www
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    ports:
      - "8071:80"
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: family_tree
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3372:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql_data:
